### ISSUE TITLE
I'd like to ask a question about full datasets

### ISSUE THREAD

**Issue by kakarotssgss** [aburguera/NNLOOP#1]
Dear Professor, I feel that your research on slam is very cutting-edge. I have learned a lot from your nnloop paper, so I want to reproduce your code to deepen my understanding. However, at present, there is no full datasets and can not be reproduced. May I use your full datasets

**Comment by aburguera** [comment]
Dear kakarotssgss,

The datasets are not public, but you can check the following link:

[https://github.com/srv/NetHALOC_Keras_Python](https://github.com/srv/NetHALOC_Keras_Python)

There is a dataset folder (containing only the TXT part of the datasets) and information in the README about how to download the images. If I am not wrong, the format is compatible with NNLOOP or, in case they are not, only minor changes are necessary.

Hope this helps,
Toni

**Comment by kakarotssgss** [comment]
Dear Professor,

 I received the dataset in the link you sent. Thank you very much for your help, which is very important for my research in the direction of underwater slam. Spain is a beautiful country and a tourist kingdom. 

I wish you good health, success in your work!

Best wishes，
kakarotssgss
